# Site settings
title: tttool, das Schweizer Taschenmesser für den Tiptoi-Bastler
tag_text: tttool, das Tiptoi-Bastler-Tool
description: tttool, das Schweizer Taschenmesser für den Tiptoi-Bastler

# Build settings
markdown: kramdown

exclude: ["README.md"]
