# Site settings
title: tttool, das Schweizer Taschenmesser für den Tiptoi-Bastler
tag_text: tttool
tag_subtitle: Das Schweizer Taschenmesser für den Tiptoi-Bastler
description: tttool, das Schweizer Taschenmesser für den Tiptoi-Bastler

# Build settings
markdown: kramdown

exclude: ["README.md"]
